### ISSUE TITLE
Doesn't work in windows

### ISSUE THREAD

**Issue by andrejgorin** [dlech/vscode-chmod#3] opened 2018-10-18 13:37 UTC
It would be nice if this extension could make files executable in Windows, too. At the moment I know only one way to do it in Windows:
`C:\Users\foo>git update-index --chmod=+x bar.py`

**Comment by dlech** [comment] 2018-10-18 16:58
Duplicate of #2.

**Closed by dlech** 2018-10-18 16:58 UTC
Labels: duplicate
